services:
  # --- Ngelmak Web (Frontend) ---
  nginx:
    build: .
    image: ngelmak-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/certs:/etc/nginx/ssl:ro
    networks:
      - ngelmak-net
    restart: unless-stopped

networks:
  ngelmak-net:
    external: true
